### ISSUE TITLE
Curious how you add the headers

### ISSUE THREAD

**Issue by sooheon** [martinklepsch/martinklepsch.org#3]
Metadata such as date-published and uuid seem like they must be automated by something, but I cant seem to find the code for it. Is this something that perun handles? Also is date-published ever different from the date in the title of your markdown file? Is it all just reconciled by hand? Thanks for the great resource.

**Comment by martinklepsch** [comment]
I think the date in the filename is just a convention I carried over from using Jekyll. So I guess they're usually (always?) the same. I'll close this with the suggestion to ask further questions in #perun on the clojurians slack (http://clojurians.net) which you've already found 👍
